version: '2'
services:
  spring-boot:
    image: shopie:latest
    container_name: shopie
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - spring-cloud-network
    depends_on:
      - database
    ports:
      - 8080:8080

  database:
    image: postgresql
    container_name: postgresql
    build:
      context: .
      dockerfile: db/Dockerfile
    networks:
      - spring-cloud-network
    ports:
      - 5432:5432

networks:
  spring-cloud-network:
    driver: bridge